/**
 * Interactive Artifacts  -  browse, view, and mount artifact boards from ANY repo.
 * Roots are configured in roots.json beside the plugin's Python half; a board is
 * identified by the key '<root>/<id>' and rows carry a root badge once boards come
 * from more than one repo. A bare id still means the default root, so a cache or a
 * stored selection written by the single-root version keeps resolving.
 * Folder name must equal id. Loads uncompiled: jsx() only, no JSX syntax.
 *
 * Deployed copy must be at $HERMES_HOME/desktop-plugins/interactive-artifacts/
 *  -  that is the only path the app watches. This file is the source of truth;
 * run deploy.cmd (sibling) after editing or the app keeps the old build.
 */
import {
  Badge,
  Button,
  EmptyState,
  GlyphSpinner,
  KEYBINDS_AREA,
  PALETTE_AREA,
  PANES_AREA,
  ROUTES_AREA,
  SIDEBAR_NAV_AREA,
  ScrollArea,
  SearchField,
  Separator,
  atom,
  cn,
  haptic,
  host,
  useValue
} from '@hermes/plugin-sdk'
import { useEffect, useState } from 'react'
import { jsx, jsxs } from 'react/jsx-runtime'

// Only used to synthesise an index_path for a cached row that predates the backend
// sending one. Boards now come from any repo listed in the plugin's roots.json, so
// this is a last-resort guess for the DEFAULT root, never the definition of one.
var FALLBACK_ROOT = 'C:/Users/bottl/hermes-artifacts/artifacts'
var CACHE_KEY = 'boardCache'
var SORT_KEY = 'sortMode'
var WORKSPACE_ID = 'interactive-artifacts.board'

/**
 * Identity of a board.
 *
 * Multi-root rows carry `key` ('<root>/<id>', e.g. 'findev/spy-flow') because two
 * repos may legitimately both hold a board called 'overview'. Rows cached by the
 * pre-multi-root version only have `id` — the backend still resolves a bare id
 * against the default root, so an old cache keeps working until the next load().
 */
function keyOf(it) {
  return (it && (it.key || it.id)) || ''
}

/**
 * Cross-component state. The page and the docked pane are separate React trees,
 * so they need a channel. This used to be `ctx.storage` polled on a 1500ms
 * setInterval  -  which cost a timer for the whole app lifetime and still lagged
 * up to 1.5s behind a click. An atom is the primitive `host.state` itself uses:
 * the pane subscribes with useValue and repaints on write, immediately and with
 * no timer. Storage is still written, but only for persistence across restarts.
 */
var $mounted = atom({ id: '', url: '' })

function fileUrlFromPath(p) {
  var s = String(p || '').replace(/\\/g, '/')
  if (s.indexOf('file:') === 0) return s
  if (s.charAt(0) !== '/') s = '/' + s
  return 'file://' + s
}

/** Human age for a board's generated_at. Own implementation on purpose: this
 *  file loads uncompiled with no typecheck, so an assumed helper signature
 *  would fail at runtime in front of the user rather than at build time. */
function ageLabel(value) {
  if (!value) return ''
  var t = Date.parse(value)
  if (isNaN(t)) return String(value)
  var secs = Math.floor((Date.now() - t) / 1000)
  if (secs < 0) return 'just now'
  if (secs < 60) return secs + 's ago'
  var mins = Math.floor(secs / 60)
  if (mins < 60) return mins + 'm ago'
  var hours = Math.floor(mins / 60)
  if (hours < 24) return hours + 'h ago'
  var days = Math.floor(hours / 24)
  if (days < 30) return days + 'd ago'
  var months = Math.floor(days / 30)
  if (months < 12) return months + 'mo ago'
  return Math.floor(months / 12) + 'y ago'
}

/** Staleness bucket -> dot colour. Boards are generated by collectors, so "when
 *  was this last refreshed" is the single most useful thing about one. */
function ageTone(value) {
  if (!value) return 'unknown'
  var t = Date.parse(value)
  if (isNaN(t)) return 'unknown'
  var days = (Date.now() - t) / 86400000
  if (days <= 1) return 'fresh'
  if (days <= 7) return 'ok'
  return 'stale'
}

var TONE_CLASS = {
  fresh: 'bg-(--ui-success-foreground)',
  ok: 'bg-(--ui-warning-foreground)',
  stale: 'bg-(--ui-danger-foreground)',
  unknown: 'bg-(--ui-text-tertiary)'
}

function Dot(props) {
  return jsx('span', {
    className: cn('inline-block size-1.5 shrink-0 rounded-full', TONE_CLASS[props.tone] || TONE_CLASS.unknown),
    title: props.title || ''
  })
}

/**
 * The renderer cannot enumerate a directory (ctx.os exposes no listing API), so the
 * offline fallback is the last list the backend actually served, cached in storage.
 * A hardcoded id list silently goes stale every time a board is added or removed.
 */
function cacheItems(ctx, list) {
  try {
    ctx.storage.set(CACHE_KEY, JSON.stringify(list || []))
  } catch (e) {
    /* cache is best-effort */
  }
}

function cachedItems(ctx) {
  var raw
  try {
    raw = ctx.storage.get(CACHE_KEY, '')
  } catch (e) {
    return []
  }
  if (!raw) return []
  var parsed
  try {
    parsed = JSON.parse(raw)
  } catch (e) {
    return []
  }
  if (!parsed || typeof parsed.length !== 'number') return []
  var out = []
  var i
  for (i = 0; i < parsed.length; i++) {
    var it = parsed[i]
    if (!it || !it.id) continue
    var path = it.index_path || (FALLBACK_ROOT + '/' + it.id + '/index.html')
    out.push({
      id: it.id,
      key: keyOf(it),
      root: it.root || '',
      refreshable: it.refreshable !== false,
      title: it.title || it.id,
      description: it.description || '',
      generated_at: it.generated_at || '',
      index_path: path,
      file_url: it.file_url || fileUrlFromPath(path)
    })
  }
  return out
}

function Viewer(props) {
  var url = props.url
  if (!url) {
    return jsx(EmptyState, { title: 'Pick a board', description: 'Select an artifact on the left.' })
  }
  var webviewOk = typeof window !== 'undefined' && typeof window.HTMLWebViewElement !== 'undefined'
  if (webviewOk) {
    return jsx('webview', {
      src: url,
      partition: 'persist:interactive-artifacts',
      style: { width: '100%', height: '100%', border: 0, display: 'flex', flex: 1 }
    })
  }
  return jsx('iframe', {
    src: url,
    title: 'artifact-board',
    className: 'h-full w-full border-0',
    sandbox: 'allow-scripts'
  })
}

/** Mount a board: shared atom (instant, for the docked pane) + storage
 *  (persistence). Both, always  -  they serve different lifetimes. */
function setMounted(ctx, item) {
  if (!item) return
  $mounted.set({ id: keyOf(item), url: item.file_url })
  try {
    ctx.storage.set('mountedId', keyOf(item))
    ctx.storage.set('mountedUrl', item.file_url)
  } catch (e) {
    /* storage is best-effort; the atom already carries this session */
  }
}

function BoardPage(props) {
  var ctx = props.ctx
  var itemsState = useState(null)
  var items = itemsState[0]
  var setItems = itemsState[1]
  var errState = useState('')
  var err = errState[0]
  var setErr = errState[1]
  var selState = useState(function () {
    // Restore the last board instead of snapping back to the first one. The old
    // code wrote `lastId` on every click and never read it, so the selection was
    // silently discarded on every mount.
    try {
      return ctx.storage.get('lastId', '')
    } catch (e) {
      return ''
    }
  })
  var selected = selState[0]
  var setSelected = selState[1]
  var qState = useState('')
  var q = qState[0]
  var setQ = qState[1]
  var loadState = useState(true)
  var loading = loadState[0]
  var setLoading = loadState[1]
  var busyState = useState('')
  var busy = busyState[0]
  var setBusy = busyState[1]
  var backendState = useState(false)
  var backendOk = backendState[0]
  var setBackendOk = backendState[1]
  var sortState = useState(function () {
    try {
      return ctx.storage.get(SORT_KEY, 'recent')
    } catch (e) {
      return 'recent'
    }
  })
  var sortMode = sortState[0]
  var setSortMode = sortState[1]

  function chooseSelection(list, current) {
    var i
    for (i = 0; i < list.length; i++) {
      if (keyOf(list[i]) === current) return current
    }
    return list.length ? keyOf(list[0]) : ''
  }

  function applyList(list, fromBackend) {
    setItems(list)
    setBackendOk(!!fromBackend)
    if (list.length) setSelected(function (cur) { return chooseSelection(list, cur) })
  }

  function load() {
    setLoading(true)
    return ctx.rest('/items').then(function (data) {
      var list = (data && data.items) ? data.items : []
      var rootNames = (data && data.roots ? data.roots : []).map(function (r) { return r.name }).join(', ')
      setErr(list.length
        ? ''
        : ('Backend reachable but no complete boards found in ' + (rootNames || 'any configured root') +
           '. A board is <root>/<boards>/<id>/ with artifact.json + index.html.'))
      cacheItems(ctx, list)
      applyList(list, true)
      setLoading(false)
      return list
    }).catch(function () {
      var cached = cachedItems(ctx)
      if (cached.length) {
        setErr('Dashboard backend unreachable  -  showing the last known board list. Boards still open from disk, but Refresh is unavailable until the gateway dashboard is running.')
      } else {
        setErr('Dashboard backend unreachable and no cached board list yet. Start the gateway dashboard (hermes gateway run) so the plugin API at /api/plugins/interactive-artifacts can respond.')
      }
      applyList(cached, false)
      setLoading(false)
      return []
    })
  }

  useEffect(function () {
    load()
  }, [])

  // Keep the selection persisted so the next mount restores it.
  useEffect(function () {
    if (!selected) return
    try {
      ctx.storage.set('lastId', selected)
    } catch (e) {
      /* best-effort */
    }
  }, [selected])

  var selectedItem = null
  var filtered = []
  // Distinct roots present in the CURRENT list, not the configured count: a
  // configured-but-empty repo should not switch on per-row root badges.
  var rootsSeen = {}
  var multiRoot = false
  if (items) {
    for (var ri = 0; ri < items.length; ri++) {
      var rn = items[ri].root || ''
      if (rn) rootsSeen[rn] = true
    }
    multiRoot = Object.keys(rootsSeen).length > 1
  }
  if (items) {
    var i
    var needle = (q || '').toLowerCase()
    for (i = 0; i < items.length; i++) {
      var it = items[i]
      // Root is part of the haystack so typing "findev" narrows to one repo —
      // the cheapest possible "filter by repo" without another control.
      var hay = (keyOf(it) + ' ' + (it.root || '') + ' ' + (it.title || '') + ' ' + (it.description || '')).toLowerCase()
      if (!needle || hay.indexOf(needle) !== -1) filtered.push(it)
      if (keyOf(it) === selected) selectedItem = it
    }
    if (sortMode === 'recent') {
      filtered.sort(function (a, b) {
        var ta = Date.parse(a.generated_at || '')
        var tb = Date.parse(b.generated_at || '')
        if (isNaN(ta) && isNaN(tb)) return String(a.title || a.id).localeCompare(String(b.title || b.id))
        if (isNaN(ta)) return 1
        if (isNaN(tb)) return -1
        return tb - ta
      })
    } else {
      filtered.sort(function (a, b) {
        return String(a.title || a.id).localeCompare(String(b.title || b.id))
      })
    }
  }

  function mountPane() {
    if (!selectedItem) return
    setMounted(ctx, selectedItem)
    haptic('tap')
    host.notify({ kind: 'info', message: 'Mounted ' + keyOf(selectedItem) + ' in the Interactive pane.' })
  }

  /** Dock the board as a real tab in the main workspace zone AND reveal it.
   *  The pane route needs the user to find the pane; this does not. */
  function openAsTab() {
    if (!selectedItem) return
    var item = selectedItem
    setMounted(ctx, item)
    haptic('tap')
    try {
      if (typeof host.openWorkspace === 'function') {
        host.openWorkspace(WORKSPACE_ID, {
          title: item.title || keyOf(item),
          minWidth: '480px',
          render: function () { return jsx(Viewer, { url: item.file_url }) }
        })
      } else {
        host.navigate('/interactive-artifacts')
      }
    } catch (e) {
      host.notify({ kind: 'error', message: 'Could not dock the board: ' + (e && e.message ? e.message : 'unknown error') })
    }
  }

  function reveal() {
    if (!selectedItem || !selectedItem.index_path) return
    ctx.os.revealPath(selectedItem.index_path)
  }

  function openExternal() {
    if (!selectedItem || !selectedItem.file_url) return
    ctx.os.openExternal(selectedItem.file_url)
  }

  function copyPath() {
    if (!selectedItem || !selectedItem.index_path) return
    ctx.os.writeClipboard(selectedItem.index_path)
    haptic('tap')
    host.notify({ kind: 'info', message: 'Copied path for ' + keyOf(selectedItem) })
  }

  function refreshOne(id) {
    return ctx.rest('/refresh', { method: 'POST', body: { id: id } })
  }

  function doRefresh() {
    if (!selected || !backendOk || busy) return
    setBusy('one')
    refreshOne(selected).then(function (res) {
      setBusy('')
      haptic('tap')
      load()
      if (res && res.item) setSelected(keyOf(res.item))
    }).catch(function (e) {
      setBusy('')
      var detail = (e && (e.detail || e.message)) ? String(e.detail || e.message) : ''
      host.notify({
        kind: 'error',
        message: detail ? ('Refresh failed: ' + detail) : 'Refresh failed  -  the collector returned no detail.'
      })
    })
  }

  /** Refresh every visible board, sequentially. Collectors shell out to
   *  tools/refresh.py with a 120s timeout each, so firing 12 at once would
   *  stampede the backend; one at a time keeps it answerable and lets a single
   *  failure name the board that broke instead of failing the whole batch. */
  function doRefreshAll() {
    if (!backendOk || busy || !filtered.length) return
    // A root with no collector cannot be refreshed; queueing it only buys a
    // guaranteed "tool_missing" and a misleading failure count.
    var queue = filtered.filter(function (it) { return it.refreshable !== false })
                        .map(function (it) { return keyOf(it) })
    if (!queue.length) {
      host.notify({ kind: 'info', message: 'No refreshable boards in view (none of these roots ship a collector).' })
      return
    }
    var failed = []
    setBusy('all')

    function step(n) {
      if (n >= queue.length) {
        setBusy('')
        load()
        haptic('tap')
        if (failed.length) {
          host.notify({
            kind: 'error',
            message: 'Refreshed ' + (queue.length - failed.length) + '/' + queue.length + ' boards. Failed: ' + failed.join(', ')
          })
        } else {
          host.notify({ kind: 'info', message: 'Refreshed all ' + queue.length + ' boards.' })
        }
        return
      }
      refreshOne(queue[n]).then(function () {
        step(n + 1)
      }).catch(function () {
        failed.push(queue[n])
        step(n + 1)
      })
    }

    step(0)
  }

  if (loading && !items) {
    return jsx('div', { className: 'flex h-full items-center justify-center', children: jsx(GlyphSpinner, {}) })
  }

  var sortButton = function (mode, label) {
    return jsx(Button, {
      size: 'sm',
      variant: sortMode === mode ? 'secondary' : 'ghost',
      onClick: function () {
        setSortMode(mode)
        try { ctx.storage.set(SORT_KEY, mode) } catch (e) { /* best-effort */ }
      },
      children: label
    })
  }

  return jsxs('div', {
    className: 'flex h-full min-h-0 flex-col',
    children: [
      jsxs('div', {
        className: 'flex items-center gap-2 px-3 py-2',
        children: [
          jsx('div', { className: 'font-medium', children: 'Interactive artifacts' }),
          jsx(Badge, { children: items ? String(items.length) : '0' }),
          backendOk ? null : jsx(Badge, { children: 'offline' }),
          jsx('div', {
            className: 'ml-auto flex items-center gap-1',
            children: jsxs('div', {
              className: 'flex items-center gap-1',
              children: [
                jsx(Button, { size: 'sm', variant: 'ghost', onClick: load, children: 'Reload' }),
                jsx(Button, {
                  size: 'sm',
                  variant: 'ghost',
                  disabled: !backendOk || !!busy || !filtered.length,
                  onClick: doRefreshAll,
                  children: busy === 'all' ? 'Refreshing all...' : 'Refresh all'
                }),
                jsx(Button, {
                  size: 'sm',
                  variant: 'ghost',
                  disabled: !backendOk || !!busy || !selected,
                  onClick: doRefresh,
                  children: busy === 'one' ? 'Refreshing...' : 'Refresh'
                }),
                jsx(Button, { size: 'sm', variant: 'ghost', onClick: mountPane, disabled: !selected, children: 'Mount pane' }),
                jsx(Button, { size: 'sm', onClick: openAsTab, disabled: !selected, children: 'Open as tab' })
              ]
            })
          })
        ]
      }),
      err ? jsx('div', { className: 'px-3 pb-2 text-xs text-(--ui-text-tertiary)', children: err }) : null,
      jsxs('div', {
        className: 'flex min-h-0 flex-1',
        children: [
          jsxs('div', {
            className: 'flex w-[260px] shrink-0 flex-col border-r border-(--ui-stroke-secondary)',
            children: [
              jsx('div', { className: 'p-2', children: jsx(SearchField, { value: q, onChange: setQ, placeholder: 'Filter boards...' }) }),
              jsxs('div', {
                className: 'flex items-center gap-1 px-2 pb-1',
                children: [
                  jsx('span', { className: 'text-[0.6875rem] text-(--ui-text-tertiary)', children: 'Sort' }),
                  sortButton('recent', 'Recent'),
                  sortButton('name', 'A-Z')
                ]
              }),
              jsx(ScrollArea, {
                className: 'min-h-0 flex-1',
                children: filtered.length ? filtered.map(function (it) {
                  var active = keyOf(it) === selected
                  var tone = ageTone(it.generated_at)
                  return jsx('button', {
                    type: 'button',
                    title: it.description || it.id,
                    className: cn(
                      'flex w-full flex-col items-start gap-0.5 px-3 py-2 text-left text-sm',
                      active ? 'bg-(--chrome-action-hover)' : 'hover:bg-(--chrome-action-hover)'
                    ),
                    onClick: function () {
                      setSelected(keyOf(it))
                    },
                    onDoubleClick: function () {
                      setSelected(keyOf(it))
                      setMounted(ctx, it)
                    },
                    children: jsxs('span', {
                      className: 'w-full',
                      children: [
                        jsxs('span', {
                          className: 'flex items-center gap-1.5',
                          children: [
                            jsx(Dot, { tone: tone, title: it.generated_at || 'never generated' }),
                            jsx('span', { className: 'truncate font-medium', children: it.title || it.id })
                          ]
                        }),
                        jsxs('span', {
                          className: 'flex items-center gap-1.5 pl-3 text-[0.6875rem] text-(--ui-text-tertiary)',
                          children: [
                            // Only worth the pixels once boards actually come from
                            // more than one repo; with a single root it is noise.
                            multiRoot && it.root
                              ? jsx('span', { className: 'shrink-0 rounded-sm bg-(--chrome-action-hover) px-1', children: it.root })
                              : null,
                            it.generated_at ? jsx('span', { children: ageLabel(it.generated_at) }) : null
                          ]
                        })
                      ]
                    })
                  }, keyOf(it))
                }) : jsx(EmptyState, {
                  title: q ? 'No match' : 'No boards',
                  description: q
                    ? 'Nothing matches "' + q + '".'
                    : 'No complete boards in any configured root. Add one at <root>/<boards>/<id>/ with artifact.json + index.html, or edit roots.json.'
                })
              })
            ]
          }),
          jsxs('div', {
            className: 'flex min-w-0 flex-1 flex-col',
            children: [
              jsxs('div', {
                className: 'flex items-center gap-2 px-3 py-1.5 text-xs text-(--ui-text-tertiary)',
                children: [
                  jsx('span', { className: 'truncate', children: selectedItem ? (selectedItem.title + '  -  ' + keyOf(selectedItem)) : ' - ' }),
                  selectedItem && selectedItem.generated_at
                    ? jsx('span', { className: 'shrink-0', children: '- ' + ageLabel(selectedItem.generated_at) })
                    : null,
                  jsx('div', {
                    className: 'ml-auto flex gap-1',
                    children: jsxs('div', {
                      className: 'flex gap-1',
                      children: [
                        jsx(Button, { size: 'sm', variant: 'ghost', onClick: copyPath, disabled: !selectedItem, children: 'Copy path' }),
                        jsx(Button, { size: 'sm', variant: 'ghost', onClick: reveal, disabled: !selectedItem, children: 'Reveal' }),
                        jsx(Button, { size: 'sm', variant: 'ghost', onClick: openExternal, disabled: !selectedItem, children: 'Open' })
                      ]
                    })
                  })
                ]
              }),
              jsx(Separator, {}),
              jsx('div', { className: 'min-h-0 flex-1', children: jsx(Viewer, { url: selectedItem ? selectedItem.file_url : '' }) })
            ]
          })
        ]
      })
    ]
  })
}

function BoardPane(props) {
  var ctx = props.ctx
  var mounted = useValue($mounted)

  // Restore the last mounted board once, so a fresh app start shows the pane
  // populated instead of empty. After that the atom is authoritative.
  useEffect(function () {
    if (mounted.url) return
    var url = ''
    var id = ''
    try {
      url = ctx.storage.get('mountedUrl', '')
      id = ctx.storage.get('mountedId', '')
    } catch (e) {
      return
    }
    if (url) $mounted.set({ id: id, url: url })
  }, [])

  if (!mounted.url) {
    return jsx('div', {
      className: 'flex h-full items-center p-3 text-sm text-(--ui-text-tertiary)',
      children: 'Mount a board from Interactive -> Mount pane.'
    })
  }
  return jsx(Viewer, { url: mounted.url })
}

export default {
  id: 'interactive-artifacts',
  name: 'Interactive Artifacts',
  defaultEnabled: true,
  register: function (ctx) {
    ctx.register({
      id: 'page',
      area: ROUTES_AREA,
      data: { path: '/interactive-artifacts' },
      render: function () { return jsx(BoardPage, { ctx: ctx }) }
    })
    ctx.register({
      id: 'nav',
      area: SIDEBAR_NAV_AREA,
      data: { path: '/interactive-artifacts', label: 'Interactive', codicon: 'type-hierarchy' }
    })
    ctx.register({
      id: 'pane',
      area: PANES_AREA,
      title: 'interactive',
      data: { placement: 'right', width: '420px' },
      render: function () { return jsx(BoardPane, { ctx: ctx }) }
    })
    ctx.register({
      id: 'open',
      area: PALETTE_AREA,
      data: {
        id: 'interactive-artifacts.open',
        label: 'Interactive Artifacts: Open boards',
        hint: 'Browse hermes-artifacts boards',
        keywords: ['artifact', 'board', 'dashboard', 'widget'],
        run: function () { host.navigate('/interactive-artifacts') }
      }
    })
    ctx.register({
      id: 'open-last',
      area: PALETTE_AREA,
      data: {
        id: 'interactive-artifacts.open-last',
        label: 'Interactive Artifacts: Reopen last board as tab',
        hint: 'Dock the most recently mounted board',
        keywords: ['artifact', 'board', 'tab', 'reopen'],
        run: function () {
          var cur = $mounted.get()
          var url = cur.url
          var id = cur.id
          if (!url) {
            try {
              url = ctx.storage.get('mountedUrl', '')
              id = ctx.storage.get('mountedId', '')
            } catch (e) { /* best-effort */ }
          }
          if (!url) {
            host.notify({ kind: 'info', message: 'No board mounted yet  -  open one from Interactive first.' })
            host.navigate('/interactive-artifacts')
            return
          }
          $mounted.set({ id: id, url: url })
          try {
            if (typeof host.openWorkspace === 'function') {
              host.openWorkspace(WORKSPACE_ID, {
                title: id || 'Board',
                minWidth: '480px',
                render: function () { return jsx(Viewer, { url: url }) }
              })
            } else {
              host.navigate('/interactive-artifacts')
            }
          } catch (e) {
            host.navigate('/interactive-artifacts')
          }
        }
      }
    })
    ctx.register({
      id: 'keybind-open',
      area: KEYBINDS_AREA,
      data: {
        id: 'interactive-artifacts.open',
        label: 'Open Interactive Artifacts',
        category: 'Interactive Artifacts',
        defaults: ['mod+shift+i'],
        run: function () { host.navigate('/interactive-artifacts') }
      }
    })
  }
}
